name: Build and Push Docker Image

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.ROSE2226 }}" | docker login -u "dab8106" --password-Athienoritah@24
        docker image build -t dab8106/pyflask:latest .
        docker push dab8106/pyflask:latest

