name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.Rose@2226 }}" | docker login -u "${{ secrets.AKOTH_ROSEMARY }}" --password-stdin

      - name: Build Docker image
        run: docker image build -t ${{ secrets.DOCKER_USERNAME }}/pyflask:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/pyflask:latest
